name: heyflutter
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_staggered_grid_view: ^0.7.0
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  hooks_riverpod: ^2.4.3
  riverpod_annotation: ^2.2.0
  yoda:
    git:
      url: https://github.com/alnitak/yoda.git
      ref: v1.0.2

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.5.3
  flutter_test:
    sdk: flutter

  # dart run build_runner watch -d
  riverpod_generator: ^2.3.3
  riverpod_lint: ^2.1.1
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/  
