import 'package:heyflutter/model/plant_model.dart';

/// hard-coded db items
final dummyList = <PlantModel>[
  const PlantModel(
    imageName: [
      'assets/1.png',
      'assets/2.png',
      'assets/3.png',
      'assets/4.png',
      'assets/5.png',
      'assets/6.png',
      'assets/7.png',
      'assets/8.png',
    ],
    name: 'Echeveria',
    descr: "Echeveria is a stunning succulent known for its beautiful rosette leaves. It's perfect for indoor or outdoor gardens.",
    shortDescr: 'Succulent with rosette leaves',
    price: 12.99,
    height: (min: 25.0, max: 30.0),
    temp: (min: 20, max: 25),
    pot: 'Ciramic Pot',
    favourite: false,
  ),
  const PlantModel(
    imageName: [
      'assets/2.png',
      'assets/3.png',
      'assets/4.png',
      'assets/5.png',
      'assets/6.png',
      'assets/7.png',
      'assets/8.png',
      'assets/1.png',
    ],
    name: 'Jade Plant',
    descr: 'The Jade Plant, often called the lucky money tree, is a popular choice for its vibrant green leaves and Feng Shui significance.',
    shortDescr: 'Lucky money tree',
    price: 19.99,
    height: (min: 65.0, max: 110.0),
    temp: (min: 20, max: 25),
    pot: 'Ciramic Pot',
    favourite: false,
  ),
  const PlantModel(
    imageName: [
      'assets/3.png',
      'assets/4.png',
      'assets/5.png',
      'assets/6.png',
      'assets/7.png',
      'assets/8.png',
      'assets/1.png',
      'assets/2.png',
    ],
    name: 'Aloe Vera',
    descr: 'Aloe Vera, a medicinal succulent, is well-known for its healing properties and is a great addition to any home garden.',
    shortDescr: 'Medicinal succulent',
    price: 34,
    height: (min: 125.0, max: 220.0),
    temp: (min: -273.15, max: 2),
    pot: 'Ciramic Pot',
    favourite: false,
  ),
  const PlantModel(
    imageName: [
      'assets/4.png',
      'assets/5.png',
      'assets/6.png',
      'assets/7.png',
      'assets/8.png',
      'assets/1.png',
      'assets/2.png',
      'assets/3.png',
    ],
    name: 'Sedum',
    descr: 'Sedum is a low-maintenance beauty, with fleshy leaves and vibrant blooms, making it a favorite for garden enthusiasts.',
    shortDescr: 'Low-maintenance beauty',
    price: 50,
    height: (min: 2.0, max: 12.0),
    temp: (min: 10, max: 30),
    pot: 'Ciramic Pot',
    favourite: false,
  ),
  const PlantModel(
    imageName: [
      'assets/5.png',
      'assets/6.png',
      'assets/7.png',
      'assets/8.png',
      'assets/1.png',
      'assets/2.png',
      'assets/3.png',
      'assets/4.png',
    ],
    name: 'Agave',
    descr: 'with its spike-tipped leaves, adds a touch of desert elegance to any garden or landscape.',
    shortDescr: 'Spike-tipped succulent',
    price: 99.99,
    height: (min: 10.0, max: 45.0),
    temp: (min: 15, max: 35),
    pot: 'Ciramic Pot',
    favourite: false,
  ),
  const PlantModel(
    imageName: [
      'assets/6.png',
      'assets/7.png',
      'assets/8.png',
      'assets/1.png',
      'assets/2.png',
      'assets/3.png',
      'assets/4.png',
      'assets/5.png',
    ],
    name: 'Kalanchoe',
    descr: 'Kalanchoe is a colorful and compact fat plant, perfect for small spaces or as a vibrant houseplant.',
    shortDescr: 'Colorful and compact',
    price: 2.99,
    height: (min: 1.0, max: 500.0),
    temp: (min: 21, max: 29),
    pot: 'Ciramic Pot',
    favourite: false,
  ),
  const PlantModel(
    imageName: [
      'assets/7.png',
      'assets/8.png',
      'assets/1.png',
      'assets/2.png',
      'assets/3.png',
      'assets/4.png',
      'assets/5.png',
      'assets/6.png',
    ],
    name: 'Haworthia',
    descr: 'Haworthia, with its striped leaves, is a stunning choice for those looking to add unique textures to their succulent collection.',
    shortDescr: 'Striped and stunning',
    price: 35.01,
    height: (min: 4.0, max: 430.0),
    temp: (min: 0, max: 225),
    pot: 'Ciramic Pot',
    favourite: false,
  ),
  const PlantModel(
    imageName: [
      'assets/8.png',
      'assets/1.png',
      'assets/2.png',
      'assets/3.png',
      'assets/4.png',
      'assets/5.png',
      'assets/6.png',
      'assets/7.png',
    ],
    name: 'Panda Plant',
    descr: 'The Panda Plant is a fuzzy succulent delight, known for its adorable appearance and ease of care.',
    shortDescr: 'Fuzzy succulent delight',
    price: 14.99,
    height: (min: 5.0, max: 30.0),
    temp: (min: 5, max: 12),
    pot: 'Ciramic Pot',
    favourite: false,
  ),
];
