import 'package:heyflutter/model/plant_model.dart';

/// hard-coded db items
final dummyList = <PlantModel>[
  const PlantModel(
    imageName: [
      'assets/1.png',
      'assets/1.png',
      'assets/1.png',
    ],
    name: 'Echeveria',
    descr: "Echeveria is a stunning succulent known for its beautiful rosette leaves. It's perfect for indoor or outdoor gardens.",
    shortDescr: 'Succulent with rosette leaves',
    price: 12.99,
    height: (min: 25.0, max: 30.0),
    temp: (min: 20, max: 25),
    pot: 'pot1',
    favourite: false,
  ),
  const PlantModel(
    imageName: [
      'assets/2.png',
      'assets/2.png',
      'assets/2.png',
    ],
    name: 'Jade Plant',
    descr: 'The Jade Plant, often called the lucky money tree, is a popular choice for its vibrant green leaves and Feng Shui significance.',
    shortDescr: 'Lucky money tree',
    price: 12.99,
    height: (min: 25.0, max: 30.0),
    temp: (min: 20, max: 25),
    pot: 'pot2',
    favourite: false,
  ),
  const PlantModel(
    imageName: [
      'assets/3.png',
      'assets/3.png',
      'assets/3.png',
    ],
    name: 'Aloe Vera',
    descr: 'Aloe Vera, a medicinal succulent, is well-known for its healing properties and is a great addition to any home garden.',
    shortDescr: 'Medicinal succulent',
    price: 12.99,
    height: (min: 25.0, max: 30.0),
    temp: (min: 20, max: 25),
    pot: 'pot3',
    favourite: false,
  ),
  const PlantModel(
    imageName: [
      'assets/4.png',
      'assets/4.png',
      'assets/4.png',
    ],
    name: 'Sedum',
    descr: 'Sedum is a low-maintenance beauty, with fleshy leaves and vibrant blooms, making it a favorite for garden enthusiasts.',
    shortDescr: 'Low-maintenance beauty',
    price: 12.99,
    height: (min: 25.0, max: 30.0),
    temp: (min: 20, max: 25),
    pot: 'pot4',
    favourite: false,
  ),
  const PlantModel(
    imageName: [
      'assets/5.png',
      'assets/5.png',
      'assets/5.png',
    ],
    name: 'Agave',
    descr: 'with its spike-tipped leaves, adds a touch of desert elegance to any garden or landscape.',
    shortDescr: 'Spike-tipped succulent',
    price: 12.99,
    height: (min: 25.0, max: 30.0),
    temp: (min: 20, max: 25),
    pot: 'pot5',
    favourite: false,
  ),
  const PlantModel(
    imageName: [
      'assets/6.png',
      'assets/6.png',
      'assets/6.png',
    ],
    name: 'Kalanchoe',
    descr: 'Kalanchoe is a colorful and compact fat plant, perfect for small spaces or as a vibrant houseplant.',
    shortDescr: 'Colorful and compact',
    price: 12.99,
    height: (min: 25.0, max: 30.0),
    temp: (min: 20, max: 25),
    pot: 'pot6',
    favourite: false,
  ),
  const PlantModel(
    imageName: [
      'assets/7.png',
      'assets/7.png',
      'assets/7.png',
    ],
    name: 'Haworthia',
    descr: 'Haworthia, with its striped leaves, is a stunning choice for those looking to add unique textures to their succulent collection.',
    shortDescr: 'Striped and stunning',
    price: 12.99,
    height: (min: 25.0, max: 30.0),
    temp: (min: 20, max: 25),
    pot: 'pot7',
    favourite: false,
  ),
  const PlantModel(
    imageName: [
      'assets/8.png',
      'assets/8.png',
      'assets/8.png',
    ],
    name: 'Panda Plant',
    descr: 'The Panda Plant is a fuzzy succulent delight, known for its adorable appearance and ease of care.',
    shortDescr: 'Fuzzy succulent delight',
    price: 12.99,
    height: (min: 25.0, max: 30.0),
    temp: (min: 20, max: 25),
    pot: 'pot8',
    favourite: false,
  ),
];
