import 'package:heyflutter/model/plant_model.dart';

/// hard-coded db items
final dummyList = <PlantModel>[
  const PlantModel(
    imageName: [
      'assets/1.png',
      'assets/1.png',
      'assets/1.png',
    ],
    name: 'name1',
    descr: 'descr1',
    shortDescr: 'shortDescr1',
    price: 12.99,
    height: (min: 25.0, max: 30.0),
    temp: (min: 20, max: 25),
    pot: 'pot1',
    favourite: false,
  ),
  const PlantModel(
    imageName: [
      'assets/2.png',
      'assets/2.png',
      'assets/2.png',
    ],
    name: 'name2',
    descr: 'descr2',
    shortDescr: 'shortDescr2',
    price: 12.99,
    height: (min: 25.0, max: 30.0),
    temp: (min: 20, max: 25),
    pot: 'pot2',
    favourite: false,
  ),
  const PlantModel(
    imageName: [
      'assets/3.png',
      'assets/3.png',
      'assets/3.png',
    ],
    name: 'name3',
    descr: 'descr3',
    shortDescr: 'shortDescr3',
    price: 12.99,
    height: (min: 25.0, max: 30.0),
    temp: (min: 20, max: 25),
    pot: 'pot3',
    favourite: false,
  ),
  const PlantModel(
    imageName: [
      'assets/4.png',
      'assets/4.png',
      'assets/4.png',
    ],
    name: 'name4',
    descr: 'descr4',
    shortDescr: 'shortDescr4',
    price: 12.99,
    height: (min: 25.0, max: 30.0),
    temp: (min: 20, max: 25),
    pot: 'pot4',
    favourite: false,
  ),
  const PlantModel(
    imageName: [
      'assets/5.png',
      'assets/5.png',
      'assets/5.png',
    ],
    name: 'name5',
    descr: 'descr5',
    shortDescr: 'shortDescr5',
    price: 12.99,
    height: (min: 25.0, max: 30.0),
    temp: (min: 20, max: 25),
    pot: 'pot5',
    favourite: false,
  ),
  const PlantModel(
    imageName: [
      'assets/6.png',
      'assets/6.png',
      'assets/6.png',
    ],
    name: 'name6',
    descr: 'descr6',
    shortDescr: 'shortDescr6',
    price: 12.99,
    height: (min: 25.0, max: 30.0),
    temp: (min: 20, max: 25),
    pot: 'pot6',
    favourite: false,
  ),
  const PlantModel(
    imageName: [
      'assets/7.png',
      'assets/7.png',
      'assets/7.png',
    ],
    name: 'name7',
    descr: 'descr7',
    shortDescr: 'shortDescr7',
    price: 12.99,
    height: (min: 25.0, max: 30.0),
    temp: (min: 20, max: 25),
    pot: 'pot7',
    favourite: false,
  ),
  const PlantModel(
    imageName: [
      'assets/8.png',
      'assets/8.png',
      'assets/8.png',
    ],
    name: 'name8',
    descr: 'descr8',
    shortDescr: 'shortDescr8',
    price: 12.99,
    height: (min: 25.0, max: 30.0),
    temp: (min: 20, max: 25),
    pot: 'pot8',
    favourite: false,
  ),
];
